Add bash for-loop

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -18,7 +18,35 @@ jobs:
           command: |
             source venv/bin/activate
             make coverage
-            coveralls
+      - run:
+          name: Push Coverage
+          command: |
+            source venv/bin/activate
+            echo "CIRCLE_PULL_REQUEST is:"
+            echo $CIRCLE_PULL_REQUEST
+            if [ -n "$CIRCLE_PULL_REQUEST" ]; then
+              coveralls debug
+              coveralls
+            else
+              for I in 1 2 3 4 5
+              do
+                PULL_REQUEST_NUMBER=$(curl -sb -H "Accept: application/json" "https://api.github.com/repos/ergeon/$CIRCLE_PROJECT_REPONAME/commits/$CIRCLE_SHA1/pulls" | python -c 'import json,sys;data=json.load(sys.stdin);print(data[0]["number"]) if data else print()')
+                if [ -n "$PULL_REQUEST_NUMBER" ]; then
+                  CI_PULL_REQUEST=$PULL_REQUEST_NUMBER coveralls debug
+                  CI_PULL_REQUEST=$PULL_REQUEST_NUMBER coveralls
+                  break
+                else
+                  echo "PR not found yet, trying again after a while."
+                  echo "Waiting for 5 seconds..."
+                  sleep 5
+                fi
+                if [[ $I == 5 ]]; then
+                  echo "Pull Request wasn't found for this commit."
+                  echo "Please re-run this build once Pull Request will be opened."
+                  exit 1
+                fi
+              done
+            fi
 
 workflows:
   deploy_and_notify:
